spring.application.name=projetoindividual

spring.datasource.url=jdbc:mysql://localhost:3306/ordemParanormal?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=isabellyC123!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver